### ISSUE TITLE
reporting a bug

### ISSUE THREAD

**Issue by hatefjhjknjhb** [mJace/SDN-SVC-Streaming-framework#1]
hi what's up everybidy.
I have used the c files whose names are streamer.c and reciever.c which use 3 different udp port for transferring NAULs, second and third port work properly but the first one which used for layer 1 does not work well, when I request statics from switches there is no any flow entry for this port and this layer I mean there is a rule Bute the transfered Bytes are 0. if u answer this problem I would be appreciated. I am f**king  confused.

**Comment by mJace** [comment]
It has been so long since last time I use this framework. 
What's your environments? Are the requirements all fits as noted in readme?

**Comment by hatefjhjknjhb** [comment]
> It has been so long since last time I use this framework. What's your environments? Are the requirements all fits as noted in readme?

hey buddy. firstly I gonna TX u for replying. I am really confused.
let's give u some details. I using this framework in mininet environment. and there are two type of traffic in the network. one is background traffic which is used Dijkstra algorithm to find a route for this type of traffic. the second one is svc traffic which I code to three layer and send them in three different udp port as the frame work. I ordered the switch to send this type of data to controller an calculate a route based on the links available bandwidth but when this type of data come to switch and switch send it to controller for finding the path and installing to corresponding switch the path dose not be installed in switches.
match fields are based on source and destination ip address and just udp destination port number.
corresponding switchs are supposed to use the flow rules which previously installed in flow table but every time which a layer 0 packet reach a switch it send it to the controller instead of using flow table. and this problem is just for svc layer 0 and layer 1 and 2 work properly.
I hope to give me a hand to finish my essay man TX.

**Comment by hatefjhjknjhb** [comment]
> It has been so long since last time I use this framework. What's your environments? Are the requirements all fits as noted in readme?

if u don't get what I said. u can easily run a controller with a layer 4 python file (which route based on source and destination  Ip or Ethernet address and also udp port number ) and a simple linear or tree topology and then send video and then dump-flow in one related switch. u will see that there are right statistics in the flow table which is installed for svc layer 1 and 2 but there are not any statics in  the one which installed for layer 0.

**Comment by mJace** [comment]
Okay... 
Looks like your problem is that the layer0 packets are not sent by switch as the flow table describes. 
Am I understand it right? If so, you should check the mininet side, technically this is not the problem of this framework.

When I using this framework, I didn't combine with a controller. I pre-calculated my route, and set them into mininet before I start the streamming.
Maybe you can try this way to avoid any possible issue.

**Comment by hatefjhjknjhb** [comment]
> Okay... Looks like your problem is that the layer0 packets are not sent by switch as the flow table describes. Am I understand it right? If so, you should check the mininet side, technically this is not the problem of this framework.
> 
> When I using this framework, I didn't combine with a controller. I pre-calculated my route, and set them into mininet before I start the streamming. Maybe you can try this way to avoid any possible issue.

yes u understood right.
look, when I install a flow rule before starting streaming for transmitting layer0 it does not still work properly but when I use another tool like iperf to generate udp traffic and send it on the same ip and udp port it works right so it makes me unwilling to revise mininet side. I appreciate u if u send me the file that u used for calculating routes.
best wishes man.

**Comment by hatefjhjknjhb** [comment]
> > Okay... Looks like your problem is that the layer0 packets are not sent by switch as the flow table describes. Am I understand it right? If so, you should check the mininet side, technically this is not the problem of this framework.
> > When I using this framework, I didn't combine with a controller. I pre-calculated my route, and set them into mininet before I start the streamming. Maybe you can try this way to avoid any possible issue.
> 
> yes u understood right. look, when I install a flow rule before starting streaming for transmitting layer0 it does not still work properly but when I use another tool like iperf to generate udp traffic and send it on the same ip and udp port it works right so it makes me unwilling to revise mininet side. I appreciate u if u send me the file that u used for calculating routes. best wishes man.

if u send me that file maybe I could change it to my purpose. thanks anyway.

**Comment by mJace** [comment]
Hi, I by-passed the mininet and run client/server at same host. 
And it works fine. Maybe you could try again?
* Ubuntu 14
* gcc/g++ 4.1.2
```
# Skip step 7 and change ip to 127.0.0.1 at step 9
8. On the client termianl (h1)
sudo ./receiver 4455 myout.264 15000 > myreceivedtrace.txt
9. On the server terminal. (h1)
sudo ./streamer temporal_originaltrace-frameno.txt 30 127.0.0.1 4455 temporal.264 1 > mysent.txt
```
If streaming on localhost without mininet works for you.
Maybe you could change your mininet with older version. 
I don't remember which version it was. Back to 2016, it should be 2.2 or 2.1.

Also I found that I there's lots of typo in Readme, `temproal` -> should be `temporal`.
I will fix that recently.

**Comment by hatefjhjknjhb** [comment]
> Hi, I by-passed the mininet and run client/server at same host. And it works fine. Maybe you could try again?
> 
> * Ubuntu 14
> * gcc/g++ 4.1.2
> 
> ```
> # Skip step 7 and change ip to 127.0.0.1 at step 9
> 8. On the client termianl (h1)
> sudo ./receiver 4455 myout.264 15000 > myreceivedtrace.txt
> 9. On the server terminal. (h1)
> sudo ./streamer temporal_originaltrace-frameno.txt 30 127.0.0.1 4455 temporal.264 1 > mysent.txt
> ```
> 
> If streaming on localhost without mininet works for you. Maybe you could change your mininet with older version. I don't remember which version it was. Back to 2016, it should be 2.2 or 2.1.
> 
> Also I found that I there's lots of typo in Readme, `temproal` -> should be `temporal`. I will fix that recently.

hey man. I need to prove some stuff and it is not possible using same host as streamer and reciever. anyway thank you. 🌹🌹

**Comment by mJace** [comment]
I understand that you would like to to some SDN stuff with this framework. 
I'm not telling you to get rid of mininet in your essay 😅, just trying to clarify the issue.

If streaming in a same host don't work in your environment. It's possible that something is wrong in your environment.
I could share my VM image that I test today with you.
If streaming works fine without mininet, then is not this framwork's bug. You might want to check what happened in your mininet.

**Comment by hatefjhjknjhb** [comment]
> I understand that you would like to to some SDN stuff with this framework. I'm not telling you to get rid of mininet in your essay 😅, just trying to clarify the issue.
> 
> If streaming in a same host don't work in your environment. It's possible that something is wrong in your environment. I could share my VM image that I test today with you. If streaming works fine without mininet, then is not this framwork's bug. You might want to check what happened in your mininet.

> I understand that you would like to to some SDN stuff with this framework. I'm not telling you to get rid of mininet in your essay 😅, just trying to clarify the issue.
> 
> If streaming in a same host don't work in your environment. It's possible that something is wrong in your environment. I could share my VM image that I test today with you. If streaming works fine without mininet, then is not this framwork's bug. You might want to check what happened in your mininet.

yes I am calculating a routing for multicasting svc video. this is my essay. if I send you the python code  as controller for installing flow rule could u test it and tell me the bug if there is?? you know I could send video and play it out  and it work fine But the routing is not what it supposed to be and
it is just does not work for layer0 the other layers work properly.

**Comment by hatefjhjknjhb** [comment]
if u would like please lemme know bro.

**Comment by hatefjhjknjhb** [comment]
yes I am calculating a routing for multicasting svc video. this is my essay. if I send you the python code as controller for installing flow rule could u test it and tell me the bug if there is?? you know I could send video and play it out and it work fine But the routing is not what it supposed to be andit is just does not work for layer0 the other layers work properly.if you would like please lemme know. TX bro. Sent from my Huawei phone-------- Original message --------From: Jace ***@***.***>Date: Tue, Jun 14, 2022, 11:13To: mJace/SDN-SVC-Streaming-framework ***@***.***>Cc: "hatef.hj" ***@***.***>, Manual ***@***.***>Subject: Re: [mJace/SDN-SVC-Streaming-framework] reporting a bug (Issue #1)

I understand that you would like to to some SDN stuff with this framework.

I'm not telling you to get rid of mininet in your essay 😅, just trying to clarify the issue.

If streaming in a same host don't work in your environment. It's possible that something is wrong in your environment.

I could share my VM image that I test today with you.

If streaming works fine without mininet, then is not this framwork's bug. You might want to check what happened in your mininet.
